services:
  online-steam-ge:
    build: .
    container_name: online-steam-ge
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cache:/bot/cache
      - ./chats.db:/bot/chats.db
